### ISSUE TITLE
Memory leak in simIM.readFromVisionSensor()

### ISSUE THREAD

**Issue by djl11** [CoppeliaRobotics/simIM#1]
With the following non-threaded code, child to a dummy object, and a single explicitly handled 1024x1024 vision sensor, running the below code causes memory usage to continually increase, as can be seen by opening htop (in ubuntu) and running the simulation.

```
function sysCall_init()
    vision_sensor = sim.getObjectHandle('Vision_sensor')
    while true do
        sim.handleVisionSensor(vision_sensor)
        im_handle = simIM.readFromVisionSensor(vision_sensor)
        simIM.destroy(im_handle)
    end
end
```

**Comment by promikeda** [comment]
Hi,

do you have a solution to this issue ? I'm facing exactly the same problem right now... 

I also tried the following : 

`simimhandles = simIM.handles()`
`for i in pairs(simimhandles) do`
`   simIM.destroy(simimhandles[i])`
`end`

br

M

**Comment by fferri** [comment]
Did you compile and install the latest version from git?

**Comment by Coppelia** [comment]
As a temporary workaround, instead of:
local img = simIM.readFromVisionSensor(s)

use:
local rawImg,resX,resY=sim.getVisionSensorCharImage(s)
local img=simIM.createFromData(resX,resY,rawImg)
